sudo: required
services:
- docker
language: java
jdk: oraclejdk8
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: uggOLpoLVec3ivkhQiaB6i62B9EVmLQXOmJwUvTpbup97gOO8Uo8NygB1S9+YuVBDuiFVIINwEHuzZ/2K4jD1AJMDg0rKGSU+X/hhmTiDBc0oIJ4Xk/OgBCHQJcB7OS/qdlo4urhG3bTONHNts5UvyJQZb+CF2HhzXdUaQTiU08xFfdu6VhdZrVPxCvLKYPNVvudsnWRxSXYrkcleN7fnWA9nT+SnvJYzCZqT5jg705hkRl3pyGrFTslIFlhi0PMYpq3dxt25QWPl+pUt9vu+Cjb5eIcKBCj7Wf8qstmwrumItDWGRQN3X4vPALg1s2DYDfHjJl6S1i9Q505n1iBgvWN5AM7vYrWLEEwxouWkb+Abk/ro7waORc/obx6py+1wgqPFeEqhIfMmkQQY77VxlElR/xUxUCSBMcYOkIihk+fYvGZ6zUTMzBZt0eGPaUMvQpSjoCLFBSIPjs4BeijV50Y61tkEsn05Lr8ehYdSfBQ+doceIumnfi9Fcr+IBeQZv2WC9TThk2qhFfqgyWxRjznLeYULHPgCwEtc8LVkH8bArNilI0moAOE/6TP2HdRFmBER6EWyWpCLUnqC/4tDGY5QSv7rGBLOMxfwd+9xqIesosOSiS7KJqNjMP3jPgW7G8TuLV3hNjKg7Q3GNuOTwQ/usXHD4Uby3qk7uni0Sc=
  - secure: lZYAhf0SbVNafUCsERC2H230O3oFE/tEIWGm82g0RFKBah6fyPIVNiZAbcdfJ5z+NO8mDG7c5ntiODMp69xJpALZL4Y+TqwaL6wMDYPUj2HjFartdftR2d44CtdYvHtq3Ar5OsyQVNZXw7eukJ9/SccQRX/PvySpkwI6ZSXDm2KLWBVjb+nEfNN+DxDF0iw700ii/LC+4UILCjXFPMJJoBmVW417+ihSzErdExWNcCLvsfv8pOjj9jlFJmj0cPHRI8b2t2/zM21ma+Q5RZz2JuISXQosaM5JvilbPWLTfJs+3qMKk4V0fRvrypOX72c34tcrM7PmHmkxZ7A6Fna6ZzxFntiDAVEmd3BXUkCu+SXdcHp90GZPTtGbc27LiLBi7DZTOEkPkmwAks2OycjxO/14b0/eBMjwMO1iY2GBxFzPZW7HgQewN/BhvEFMI/66JZ7is8GfBPXYlx4JZTMvWSfeXDXHUIpr0AladldVT7OfCWHWBGhoQbD0/E8TAEL5DhVqbQJREEnUdTe+lL49emrFX29/z1MzwvdPW4HA0hlu8KJ73sybprG8S5UbG6/CorSolyAG9Y4g0pex8WL7tDt3zVS3mbkko9QRpwvN49pZCOW7jNyCbAbuG3jNjuUS3LT77ki/18wfA71xkkKVlDhl0nKlrH0WE7JHjlkU3Uk=
  - secure: LauYGO6adgrenS93ZEgQ3N8lepGowztvwyMdLD75jI1X+UUDuwjm6nB0rIO2rrnxAXMlTqMY7U3Opo+skapBse5lNquuP8tWAaG0fqJ8HFNwA4hTmup2cBrbSMO+dr/VCPw9a9d6EtZE8cVkUJ4Ck1Qp3bpaUAnnjDDI6Yt/YvAfFx8JydiVLn1b4CRjt0gT30j5e6T4fEEQKTWMjVLtdpCe0XRQrPqAastAlojmzSQZhw1eX4w+t/Z7WScaa6m1tQn8Y8Jk9sSo14qeqh3XzwqVBLmNJYpkcGGh2KUv5hmtwlLLfUQZgR1hzabjFkAYEXBXooVS8owqSssHERryi5p5eNKgdjffv84OwQy1D2iw4J6M5B7kfyNdGLl1nOz6QmT5Os/N/6ynghfR6PW07p2xru+CZCpu8Ush3hygSIUhQFkRCUSqUOt25mtC0xK9k04W8HnSx7ZDQkmF/PDpgCt1ak5c0I/3l7Mo/eu/Gwopi3DIm53txwKwqZhBaIgpsXlwDH8aXaT8AdkXl1UHYnluv2OW1/lsH9533cNQ33PDj4eK8V/zON6AfevJsvOEuZgU07kNKiGRu/nKyS9CkzmFcD5Rm+FCLdn+poRYhjjxKLvq1D3oWX6MMdp/SqjetpectYKXlKQKk5i0Ud7uywkkUzYuOygw9g78My9SL9o=
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export CONFIG=revitbaby/piggymetrics-config
- docker build -t $CONFIG:$COMMIT ./config
- docker tag $CONFIG:$COMMIT $CONFIG:$TAG
- docker push $CONFIG
- export REGISTRY=revitbaby/piggymetrics-registry
- docker build -t $REGISTRY:$COMMIT ./registry
- docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
- docker push $REGISTRY
- export GATEWAY=revitbaby/piggymetrics-gateway
- docker build -t $GATEWAY:$COMMIT ./gateway
- docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
- docker push $GATEWAY
- export AUTH_SERVICE=revitbaby/piggymetrics-auth-service
- docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
- docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
- docker push $AUTH_SERVICE
- export ACCOUNT_SERVICE=revitbaby/piggymetrics-account-service
- docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
- docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
- docker push $ACCOUNT_SERVICE
- export STATISTICS_SERVICE=revitbaby/piggymetrics-statistics-service
- docker build -t $STATISTICS_SERVICE:$COMMIT ./statistics-service
- docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
- docker push $STATISTICS_SERVICE
- export NOTIFICATION_SERVICE=revitbaby/piggymetrics-notification-service
- docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
- docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
- docker push $NOTIFICATION_SERVICE
- export MONITORING=revitbaby/piggymetrics-monitoring
- docker build -t $MONITORING:$COMMIT ./monitoring
- docker tag $MONITORING:$COMMIT $MONITORING:$TAG
- docker push $MONITORING
- export MONGO_DB=revitbaby/piggymetrics-mongodb
- docker build -t $MONGO_DB:$COMMIT ./mongodb
- docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
- docker push $MONGO_DB
