sudo: required
services:
- docker
language: java
jdk: oraclejdk8
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: Y1CTzXOEF7QcFL1r0hVXb8qKHM7oR4i3Db/r9x3BuqzIgE1LVuCBweIKsYXnDFSbDc3pbznosrhdT76vIf1aSKlmcOOn3Uu1mxt+y6ehNwsmN+QmHkmEqknVulHJ9I9gHiRQqIlVhn8zsIF88CwYkbEGC8HtK+qfyuB+mQsswRUnumdL5OBMSjPrywz3P1V/U53aSDPMucoXUlSgeTYuS87S4i2O38+VB+zDWGOkTQ14YfB/7F19j9Ldeg41vDOacQzi76c+3m4jEXrTOOadNaevBCCqfBXX8tW0hdUvvz8mOz/nI5GDMh9RkWsfU8q7K7ruBZOo10Dp7e27FkDJTCCgHQzRA4Yi5ByoATegxJhnD8jVii6+KwboTJ5kdDs8aLT811nabDedTryay1UOaufe0DxZU8wa3hxMp406QIrTjjPX0BSzMztB7hBHU1TXLn6uvvxqyMhoalkKMC/sglWT9u0Riu0JN53c2wjjAbnZFZcIMYqKAPJb9eBTDzcxm6cEMnqL0+dbiKwsXYIifbbau9ECedagm9KtW+LUodSyzj6CGFc3598qYSJ86qcWzHK9NU3ei140YPeH57AnqLzIj9uouE5D8FwfhJ8zgrn4hfJ38F0KXTJHemT/LxGwcAEE3cFzwJDN+0KYHwhp8d0h/df87EiwFnFA+pujjGM=
  - secure: Kh1zulPfNhPqmpDx+/W2MMXynVbkVlkIDeRvAEdPFbBlyixBg+hVUbfN3dhJ82CNlECWQoOd0Xqxp0tze+RWnJkkCOo6Oj3UZtKebTi1ger8oz5sl56+tsgMM2uQD1hmJl8mK5X/idfB2t6ItkxMCn42i/nGPm/LXOPmRJWo6gregaKGrS205WnqRD+mqDPE9N6LJ900CaQekt5QUcFxu/FJSPe9GyrYquojsDukZlW2/erObO4g7dDwscYpUokCTivlcmjGbvI6//yFQUiaeXgAXRqCib+VRClCRspi1rKFE5QHag4DSae7hAJAIX2RbV8yUVnfh+/xjWDfwDVnhW4+GJdZ/eS6uZu7gPp7NtAFgTRPk4bQvCrlFd4J+vu7n2CQSv7VV12TlDfzlmYsRwXMZ3+k+FzQjIjaAO7PSpe2gFp2ZZIBrQgUHL3wu7xGhkr/WP6VrfEI0JnihY1uS4BaGvu3olZYcibIvPOpuQKwbo6uDwGRHPsMQueYrmHaeIMdrd1J5VicRsq2N4Z3f2IuAqwcyHttw95AirdJJcHykNEd6e1ohYc6sZ5v7bvTZDO0TMNcgtzNIqVDEstGuVbKnb4SOdckAa6d54xfOgtt8K0mfbfrBwH7W/iaOC2BXMfmrZebPQxObdlGVIhLbaKPM/z740yjOhr199Hgf7I=
  - secure: UT7kl3YgQdI2W8mxNjMPB7XrFSWPoJZopj1dRHRBimx9nfMYh3qLHTfAsP2gzfAYR/Bh64KPzB9gq4L79qjsvI71+sHyf7kJACKdIcd5tbWuP8YBxxAZi7iZlSeh/KbvmnYD+g+r8lOvHS0Wv3MCFUS5WEHbSkk+eQrK5A8DceqmW3QTyPJqdrYfk0EhiIMc9vrsjU8w2yrWAb+EpG4Snmtrd23BzdEHmvVQIvto7b0/IpQz9t1GevxFkkyaDfQAR3omTo4KVdu7s6WwdxiFFA9sUHN1LppdO7fFVVl8BMB+rAT0Icgcf4e9p0cYQxBME/NdUSFY39PhzjYVqcF3N+B0XRVUArYrPxXw23kAlGrgHoT+Aa+Iju/JHD+tOax5V3g+OeSjv1nUDRFgZTamwq2F+r/8f60fqFs6bFLo7azchN03wubXJ5hndooF0Xb5g54lbYb1gr3zbfl/HOxv5Hnhw6DCmVGPxhL6M5T6+ZTN6t5B0r2xqWndDYEFTO+qMTov6ej4zIg7Dzz6UXEwrFnhNpLUkiWgsBC5fTP5EejdLlltbzZlTGItA9KWTqUML+2jzgGNQMkS4af4pRGlYPmhssFkDwJDoRvGynkCWI/7Yfrf7Vhh/ON9g4Xio/BBEoaaq/HDl2I+OD+e9GSJ5RTXqW9dPvD2MKd7JpfG0nw=
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export CONFIG=revitbaby/piggymetrics-config
- docker build -t $CONFIG:$COMMIT ./config
- docker tag $CONFIG:$COMMIT $CONFIG:$TAG
- docker push $CONFIG
- export REGISTRY=revitbaby/piggymetrics-registry
- docker build -t $REGISTRY:$COMMIT ./registry
- docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
- docker push $REGISTRY
- export GATEWAY=revitbaby/piggymetrics-gateway
- docker build -t $GATEWAY:$COMMIT ./gateway
- docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
- docker push $GATEWAY
- export AUTH_SERVICE=revitbaby/piggymetrics-auth-service
- docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
- docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
- docker push $AUTH_SERVICE
- export ACCOUNT_SERVICE=revitbaby/piggymetrics-account-service
- docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
- docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
- docker push $ACCOUNT_SERVICE
- export STATISTICS_SERVICE=revitbaby/piggymetrics-statistics-service
- docker build -t $STATISTICS_SERVICE:$COMMIT ./statistics-service
- docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
- docker push $STATISTICS_SERVICE
- export NOTIFICATION_SERVICE=revitbaby/piggymetrics-notification-service
- docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
- docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
- docker push $NOTIFICATION_SERVICE
- export MONITORING=revitbaby/piggymetrics-monitoring
- docker build -t $MONITORING:$COMMIT ./monitoring
- docker tag $MONITORING:$COMMIT $MONITORING:$TAG
- docker push $MONITORING
- export MONGO_DB=revitbaby/piggymetrics-mongodb
- docker build -t $MONGO_DB:$COMMIT ./mongodb
- docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
- docker push $MONGO_DB
